services:
  api:
    build:
      context: ../../scripts/api/app
      dockerfile: Dockerfile
    image: etape_4-api:latest
    container_name: showroomprive_api
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ml_models_vol:/ml_models:ro

volumes:
  ml_models_vol:
    name: ml_models_vol
