services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: etape_4-api:latest
    container_name: showroomprive_api
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    networks:
      - projet_dst__net

networks:
  projet_dst__net:
    external: true
